### ISSUE TITLE
bring back intel mac support

### ISSUE THREAD

**Issue by jaredgreen2** [lean-dojo/LeanCopilot#98] opened 2024-07-02 14:56 UTC
there was intel mac support before, now there isnt.

**Comment by yangky11** [comment] 2024-07-08 17:45
I can no longer build LeanCopilot's cloud releases on Intel Mac since I've traded in my old Intel Mac.  However, even without cloud releases, it should be possible to build LeanCopilot locally. Did you encounter any error when using it on an Intel Mac?

**Comment by jaredgreen2** [comment] 2024-07-08 21:59
i dont know how to do that. i haven't even downloaded the model, having only followed the directions in the readme.

**Comment by yangky11** [comment] 2024-07-12 00:59
We would need:
1. What error did you encounter.
2. Exact steps to reproduce the error.

**Comment by jaredgreen2** [comment] 2024-07-12 13:34
$ lake exe LeanCopilot/download

✖ [1/17] Fetching LeanCopilot:optRelease

trace: downloading https://github.com/lean-dojo/LeanCopilot/releases/download/v1.3.3/x86_64-macOS.tar.gz

trace: .> curl -s -S -f -o ././.lake/packages/LeanCopilot/.lake/x86_64-macOS.tar.gz -L https://github.com/lean-dojo/LeanCopilot/releases/download/v1.3.3/x86_64-macOS.tar.gz

trace: stderr:

curl: (22) The requested URL returned error: 404

error: external command 'curl' exited with code 22

✖ [2/17] Fetching LeanCopilot:release

trace: downloading https://github.com/lean-dojo/LeanCopilot/releases/download/v1.3.3/x86_64-macOS.tar.gz

trace: .> curl -s -S -f -o ././.lake/packages/LeanCopilot/.lake/x86_64-macOS.tar.gz -L https://github.com/lean-dojo/LeanCopilot/releases/download/v1.3.3/x86_64-macOS.tar.gz

trace: stderr:

curl: (22) The requested URL returned error: 404

error: external command 'curl' exited with code 22

Some builds logged failures:

    LeanCopilot:optRelease
    LeanCopilot:release

error: build failed

**Comment by ericluap** [comment] 2024-07-23 23:53
I have the same error.

It is trying to download a file for Intel Mac for version 1.4.1 which does not exist.

**Comment by Peiyang-Song** [comment] 2024-08-14 06:24
Thank you all for the report of difficulty using Lean Copilot on intel mac! Although the team currently does not own a M1 Mac, we heard from another user about a similar issue, and we are resolving it in the next release. I will ping in this issue once the new release is published.

**Comment by Peiyang-Song** [comment] 2024-08-15 00:22
Thanks again for the discussion. We just had a user try Lean Copilot's latest stable release (v1.5.0), to be used with Lean's latest stable release v4.10.0, on an Intel Mac. According to their report everything works fine with this new version. You are encouraged to try it out! Feel free to open an issue if you encounter any specific difficulties.

**Closed by Peiyang-Song** 2024-08-15 00:22 UTC

**Comment by jaredgreen2** [comment] 2024-08-15 14:17
unfortunately i still get a very similar 404 as before. 
$ lake exe LeanCopilot/download
✖ [3/20] (Optional) Fetching LeanCopilot:optRelease
trace: downloading https://github.com/lean-dojo/LeanCopilot/releases/download/v1.5.1/x86_64-macOS.tar.gz
trace: .> curl -s -S -f -o ././.lake/packages/LeanCopilot/.lake/x86_64-macOS.tar.gz -L https://github.com/lean-dojo/LeanCopilot/releases/download/v1.5.1/x86_64-macOS.tar.gz
trace: stderr:
curl: (22) The requested URL returned error: 404
error: external command 'curl' exited with code 22
error: build failed
